"""Stage B of the persona demo: replay each cast turn-by-turn with LLM stand-ins.

Position k of the human cast sequence is regenerated by the same person's agent,
so the two lines have the same speakers in the same order and the same length.
The agent sees the post and the comments generated before it -- never a real
human comment, and no reply-tree hint (flat).

    python scripts/run_persona_demo.py                    # DeepSeek, resumable
    python scripts/run_persona_demo.py --provider openai --model gpt-5.6-luna
    python scripts/run_persona_demo.py --provider qwen --model qwen-plus
    python scripts/run_persona_demo.py --limit 5          # short smoke per thread
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from mas_collapse.config import load_config
from mas_collapse.simulate.persona import (
    HistoryStats,
    LLMClient,
    PersonaCard,
    agent_system_prompt,
    agent_user_prompt,
    max_tokens_for,
    visible_history_indices,
)


def _card_from_dict(d: dict) -> PersonaCard:
    stats = HistoryStats(**d["stats"])
    return PersonaCard(
        author=d["author"],
        alias=d["alias"],
        stats=stats,
        samples=d.get("samples", []),
        stance=d.get("stance", ""),
        tone=d.get("tone", ""),
        quirks=d.get("quirks", ""),
    )


def run_one_thread(
    thread: dict,
    cards: dict[str, PersonaCard],
    client: LLMClient,
    out_path: Path,
    *,
    temperature: float,
    chars_per_token: float,
    floor: int,
    ceil: int,
    limit: int,
    retries: int,
    history_source: str,
    limit_length: bool = True,
    free_max_tokens: int = 8192,
    disable_thinking: bool | None = None,
    arm: str = "",
    tier: str = "",
    history_view: dict | None = None,
    reply_max_tokens: int | None = None,
    reply_target_chars: int | None = None,
) -> dict:
    turns = thread["turns"]
    if limit:
        turns = turns[:limit]

    payload = {
        "post_id": thread["post_id"],
        "subreddit": thread["subreddit"],
        "title": thread["title"],
        "provider": client.provider,
        "provider_model": client.model,
        "arm": arm,
        "tier": tier,
        "history_view": history_view or {},
        "temperature": temperature,
        "protocol": (
            "limited history recent+random; post visible; own generated text"
            if history_view
            else "cast-only replay; post visible; generated history only; flat"
        ),
        "history_source": history_source,
        "length_limit": limit_length,
        "n_turns": len(turns),
        "human": turns,
        "generated": [],
    }
    if out_path.exists():
        prev = json.loads(out_path.read_text(encoding="utf-8"))
        if (
            prev.get("provider_model") == client.model
            and (not arm or prev.get("arm", arm) == arm)
            and prev.get("n_turns") == len(turns)
            and prev.get("history_source") == history_source
            and bool(prev.get("length_limit", True)) == limit_length
            and (not history_view or prev.get("history_view") == history_view)
        ):
            payload = prev
    done = len(payload["generated"])

    system_cache = {
        a: agent_system_prompt(c, limit_length=limit_length)
        for a, c in cards.items()
        if a in thread["cast"]
    }
    if limit_length:
        budget = {
            a: max_tokens_for(c.stats, chars_per_token, floor, ceil)
            for a, c in cards.items()
            if a in thread["cast"]
        }
        target = {a: c.stats.len_median for a, c in cards.items() if a in thread["cast"]}
    else:
        budget = {a: free_max_tokens for a in thread["cast"]}
        target = {a: None for a in thread["cast"]}
    if reply_max_tokens:
        budget = {a: int(reply_max_tokens) for a in thread["cast"]}
    if reply_target_chars is not None:
        target = {}
        for a in thread["cast"]:
            med = cards[a].stats.len_median if a in cards else 0
            target[a] = min(med, int(reply_target_chars)) if med else int(reply_target_chars)

    for i in range(done, len(turns)):
        turn = turns[i]
        author = turn["author"]
        shown = None
        if history_view:
            shown = visible_history_indices(
                len(payload["generated"]),
                recent=int(history_view["recent"]),
                earlier=int(history_view["earlier"]),
                seed=int(history_view["seed"]),
                post_id=thread["post_id"],
                step=i,
            )
        user = agent_user_prompt(
            thread["title"],
            thread["selftext"],
            payload["generated"],
            target[author],
            indices=shown,
        )
        body, err = "", ""
        for attempt in range(retries + 1):
            try:
                body = client.chat(
                    system_cache[author],
                    user,
                    max_tokens=budget[author],
                    temperature=temperature,
                    disable_thinking=disable_thinking,
                )
                if body:
                    err = ""
                    break
                err = "empty completion"
            except Exception as exc:  # noqa: BLE001 - record and keep the replay going
                err = f"{type(exc).__name__}: {exc}"
                time.sleep(1.5 * (attempt + 1))
        payload["generated"].append(
            {
                "position": turn["position"],
                "alias": turn["alias"],
                "author": author,
                "body": body,
                "n_chars": len(body),
                "human_n_chars": turn["n_chars"],
                "shown_indices": shown,
                "error": err,
            }
        )
        out_path.write_text(json.dumps(payload, ensure_ascii=False, indent=1), encoding="utf-8")
        if (i + 1) % 10 == 0 or i + 1 == len(turns):
            print(f"  [{thread['post_id']}] {i + 1}/{len(turns)}", flush=True)
    return payload


def main() -> None:
    ap = argparse.ArgumentParser(description="Replay persona-demo casts with an LLM")
    ap.add_argument("--config", default="configs/default.yaml")
    ap.add_argument("--provider", default="deepseek", choices=["deepseek", "openai", "qwen"])
    ap.add_argument("--model", default=None)
    ap.add_argument("--temperature", type=float, default=0.9)
    ap.add_argument("--limit", type=int, default=0, help="cap turns per thread (smoke)")
    ap.add_argument("--retries", type=int, default=2)
    ap.add_argument("--workers", type=int, default=3, help="threads run in parallel; turns never do")
    args = ap.parse_args()

    cfg = load_config(args.config)
    pd_cfg = cfg["persona_demo"]
    tag = pd_cfg["tag"]
    persona_dir = Path(cfg["paths"]["personas"]) / tag
    raw = json.loads((persona_dir / "cast_and_history.json").read_text(encoding="utf-8"))
    cards_blob = json.loads((persona_dir / "cards.json").read_text(encoding="utf-8"))
    cards = {a: _card_from_dict(d) for a, d in cards_blob["cards"].items()}
    history_source = cards_blob.get("history_source") or "unspecified"

    out_dir = Path(cfg["paths"]["sims"]) / tag
    out_dir.mkdir(parents=True, exist_ok=True)

    client = LLMClient.from_env(args.provider, args.model)
    total = sum(len(t["turns"]) if not args.limit else min(args.limit, len(t["turns"])) for t in raw["threads"].values())
    print(f"generating {total} comments with {client.model} (cards written by {cards_blob['model']})")

    t0 = time.perf_counter()
    jobs = []
    with ThreadPoolExecutor(max_workers=max(1, args.workers)) as pool:
        for pid, thread in raw["threads"].items():
            jobs.append(
                pool.submit(
                    run_one_thread,
                    thread,
                    cards,
                    client,
                    out_dir / f"{pid}.json",
                    temperature=args.temperature,
                    chars_per_token=float(pd_cfg["chars_per_token"]),
                    floor=int(pd_cfg["max_tokens_floor"]),
                    ceil=int(pd_cfg["max_tokens_ceil"]),
                    limit=args.limit,
                    retries=args.retries,
                    history_source=history_source,
                    limit_length=bool(pd_cfg.get("limit_reply_length", True)),
                    free_max_tokens=int(pd_cfg.get("max_tokens_free", 8192)),
                )
            )
        results = [j.result() for j in jobs]

    print(f"\ndone in {(time.perf_counter() - t0) / 60:.1f} min")
    for r in results:
        bad = sum(1 for g in r["generated"] if g["error"])
        hum = sum(g["human_n_chars"] for g in r["generated"]) / max(1, len(r["generated"]))
        sim = sum(g["n_chars"] for g in r["generated"]) / max(1, len(r["generated"]))
        print(
            f"  {r['post_id']} r/{r['subreddit']}: {len(r['generated'])} comments, "
            f"{bad} failed, mean chars human={hum:.0f} sim={sim:.0f}"
        )
    print(f"wrote {out_dir}")


if __name__ == "__main__":
    main()
