"""Stage B of the persona demo: replay each cast turn-by-turn with LLM stand-ins.

Position k of the human cast sequence is regenerated by the same person's agent,
so the two lines have the same speakers in the same order and the same length.
The agent sees the post and the comments generated before it -- never a real
human comment, and no reply-tree hint (flat).

    python scripts/run_persona_demo.py                    # DeepSeek, resumable
    python scripts/run_persona_demo.py --provider openai --model gpt-5.6-luna
    python scripts/run_persona_demo.py --limit 5          # short smoke per thread
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from mas_collapse.config import load_config
from mas_collapse.simulate.persona import (
    HistoryStats,
    LLMClient,
    PersonaCard,
    agent_system_prompt,
    agent_user_prompt,
    max_tokens_for,
)


def _card_from_dict(d: dict) -> PersonaCard:
    stats = HistoryStats(**d["stats"])
    return PersonaCard(
        author=d["author"],
        alias=d["alias"],
        stats=stats,
        samples=d.get("samples", []),
        stance=d.get("stance", ""),
        tone=d.get("tone", ""),
        quirks=d.get("quirks", ""),
    )


def run_one_thread(
    thread: dict,
    cards: dict[str, PersonaCard],
    client: LLMClient,
    out_path: Path,
    *,
    temperature: float,
    chars_per_token: float,
    floor: int,
    ceil: int,
    limit: int,
    retries: int,
) -> dict:
    turns = thread["turns"]
    if limit:
        turns = turns[:limit]

    payload = {
        "post_id": thread["post_id"],
        "subreddit": thread["subreddit"],
        "title": thread["title"],
        "provider_model": client.model,
        "temperature": temperature,
        "protocol": "cast-only replay; post visible; generated history only; flat",
        "n_turns": len(turns),
        "human": turns,
        "generated": [],
    }
    if out_path.exists():
        prev = json.loads(out_path.read_text(encoding="utf-8"))
        if prev.get("provider_model") == client.model and prev.get("n_turns") == len(turns):
            payload = prev
    done = len(payload["generated"])

    system_cache = {
        a: agent_system_prompt(c, thread["subreddit"]) for a, c in cards.items() if a in thread["cast"]
    }
    budget = {
        a: max_tokens_for(c.stats, chars_per_token, floor, ceil) for a, c in cards.items() if a in thread["cast"]
    }
    target = {a: c.stats.len_median for a, c in cards.items() if a in thread["cast"]}

    for i in range(done, len(turns)):
        turn = turns[i]
        author = turn["author"]
        user = agent_user_prompt(
            thread["title"], thread["selftext"], payload["generated"], target[author]
        )
        body, err = "", ""
        for attempt in range(retries + 1):
            try:
                body = client.chat(
                    system_cache[author],
                    user,
                    max_tokens=budget[author],
                    temperature=temperature,
                )
                if body:
                    err = ""
                    break
                err = "empty completion"
            except Exception as exc:  # noqa: BLE001 - record and keep the replay going
                err = f"{type(exc).__name__}: {exc}"
                time.sleep(1.5 * (attempt + 1))
        payload["generated"].append(
            {
                "position": turn["position"],
                "alias": turn["alias"],
                "author": author,
                "body": body,
                "n_chars": len(body),
                "human_n_chars": turn["n_chars"],
                "error": err,
            }
        )
        out_path.write_text(json.dumps(payload, ensure_ascii=False, indent=1), encoding="utf-8")
        if (i + 1) % 10 == 0 or i + 1 == len(turns):
            print(f"  [{thread['post_id']}] {i + 1}/{len(turns)}", flush=True)
    return payload


def main() -> None:
    ap = argparse.ArgumentParser(description="Replay persona-demo casts with an LLM")
    ap.add_argument("--config", default="configs/default.yaml")
    ap.add_argument("--provider", default="deepseek", choices=["deepseek", "openai"])
    ap.add_argument("--model", default=None)
    ap.add_argument("--temperature", type=float, default=0.9)
    ap.add_argument("--limit", type=int, default=0, help="cap turns per thread (smoke)")
    ap.add_argument("--retries", type=int, default=2)
    ap.add_argument("--workers", type=int, default=3, help="threads run in parallel; turns never do")
    args = ap.parse_args()

    cfg = load_config(args.config)
    pd_cfg = cfg["persona_demo"]
    tag = pd_cfg["tag"]
    persona_dir = Path(cfg["paths"]["personas"]) / tag
    raw = json.loads((persona_dir / "cast_and_history.json").read_text(encoding="utf-8"))
    cards_blob = json.loads((persona_dir / "cards.json").read_text(encoding="utf-8"))
    cards = {a: _card_from_dict(d) for a, d in cards_blob["cards"].items()}

    out_dir = Path(cfg["paths"]["sims"]) / tag
    out_dir.mkdir(parents=True, exist_ok=True)

    client = LLMClient.from_env(args.provider, args.model)
    total = sum(len(t["turns"]) if not args.limit else min(args.limit, len(t["turns"])) for t in raw["threads"].values())
    print(f"generating {total} comments with {client.model} (cards written by {cards_blob['model']})")

    t0 = time.perf_counter()
    jobs = []
    with ThreadPoolExecutor(max_workers=max(1, args.workers)) as pool:
        for pid, thread in raw["threads"].items():
            jobs.append(
                pool.submit(
                    run_one_thread,
                    thread,
                    cards,
                    client,
                    out_dir / f"{pid}.json",
                    temperature=args.temperature,
                    chars_per_token=float(pd_cfg["chars_per_token"]),
                    floor=int(pd_cfg["max_tokens_floor"]),
                    ceil=int(pd_cfg["max_tokens_ceil"]),
                    limit=args.limit,
                    retries=args.retries,
                )
            )
        results = [j.result() for j in jobs]

    print(f"\ndone in {(time.perf_counter() - t0) / 60:.1f} min")
    for r in results:
        bad = sum(1 for g in r["generated"] if g["error"])
        hum = sum(g["human_n_chars"] for g in r["generated"]) / max(1, len(r["generated"]))
        sim = sum(g["n_chars"] for g in r["generated"]) / max(1, len(r["generated"]))
        print(
            f"  {r['post_id']} r/{r['subreddit']}: {len(r['generated'])} comments, "
            f"{bad} failed, mean chars human={hum:.0f} sim={sim:.0f}"
        )
    print(f"wrote {out_dir}")


if __name__ == "__main__":
    main()
